# -*- coding: utf-8 -*-
#第一次启动时候的欢迎界面的操作
#登录/注册
reg_login='com.tongbanjie.android:id/reg_login'
#立即体验
into_main='com.tongbanjie.android:id/into_main'

#检测到新版本时的操作
#取消
cancel_item='com.tongbanjie.android:id/cancel_item'
#继续
tab_more='com.tongbanjie.android:id/tab_more'

#登陆模块
#更多模块按钮
more='com.tongbanjie.android:id/tab_more'
#更多模块的更多标签
more_label='com.tongbanjie.android:id/title'
#我的账户按钮
myaccount='com.tongbanjie.android:id/account_tip'
loginbtn='com.tongbanjie.android:id/more_account_layout'
#5.1版本更多模块的点击登陆按钮
loginbtn5='com.tongbanjie.android:id/rl_user_info'
#手机号
input_phone='com.tongbanjie.android:id/input_value'
#返回按钮
tv_left_option='com.tongbanjie.android:id/tv_left_option'
#下一步
next='com.tongbanjie.android:id/phone_next'
#密码
input_login_passwd='com.tongbanjie.android:id/user_pwd'
#登陆确定按钮
click_login_button='com.tongbanjie.android:id/login_btn'
#退出登录
logout='com.tongbanjie.android:id/logout_btn'
#注册功能
#输入验证码
verify_input='com.tongbanjie.android:id/verify_input'
#验证码重发按钮
receive_verifi_btn='com.tongbanjie.android:id/receive_verifi_btn'
#设置登陆密码
set_login_password='com.tongbanjie.android:id/set_login_password'
#完成按钮
complete_btn='com.tongbanjie.android:id/complete_btn'
#精品推荐模块的注册/登陆按钮
hot_product_login='com.tongbanjie.android:id/btn_login'

#查看用户个人信息
#用户个人信息按钮
rl_user_info='com.tongbanjie.android:id/rl_user_info'
#校验用户个人信息:账户，实名认证，身份认证，投资风格
user_name='com.tongbanjie.android:id/user_name'
full_name='com.tongbanjie.android:id/full_name'
id_card='com.tongbanjie.android:id/id_card'
tv_risk_level_value='com.tongbanjie.android:id/tv_risk_level_value'
#返回按钮
back2='com.tongbanjie.android:id/back'

#密码管理
#密码管理入口
rl_pwd_manager='com.tongbanjie.android:id/rl_pwd_manager'
#修改登录密码
change_login_pwd_layout='com.tongbanjie.android:id/change_login_pwd_layout'
#旧密码
old_password_input='com.tongbanjie.android:id/old_password_input'
#新密码
new_password_input='com.tongbanjie.android:id/new_password_input'
#确定新密码''
confilm_new_password='com.tongbanjie.android:id/confilm_new_password'
#修改按钮
modify_login_pwd='com.tongbanjie.android:id/modify_login_pwd'
#修改交易密码
rlyt_update_trans_pwd='com.tongbanjie.android:id/rlyt_update_trans_pwd'
#修改交易密码-完成
complete_btn='com.tongbanjie.android:id/complete_btn'
#修改交易密码，两次密码输入不一致的弹出框
pwd_dialog_message_text='com.tongbanjie.android:id/dialog_message_text'
#找回交易密码-按钮
rlyt_find_trade_pwd='com.tongbanjie.android:id/rlyt_find_trade_pwd'
#找回交易密码-姓名
full_name_value='com.tongbanjie.android:id/full_name_value'
#找回交易密码-身份证
input_value='com.tongbanjie.android:id/input_value'
#找回交易密码-下一步
next_btn='com.tongbanjie.android:id/next_btn'
#找回交易密码-校验
verify_input='com.tongbanjie.android:id/verify_input'
#校验-下一步
btn_next='com.tongbanjie.android:id/btn_next'
#校验修改登录密码，修改交易密码，找回交易密码成功的按钮
check_pwd_success='com.tongbanjie.android:id/change_login_pwd_layout'
#手势解锁
switcher_checkbox='com.tongbanjie.android:id/switcher_checkbox'
#创建手势解锁
btn_start_set_pattern_lock='com.tongbanjie.android:id/btn_start_set_pattern_lock'
#手势解锁-标题
title='com.tongbanjie.android:id/title'

#账户余额一系列操作
#4.3-5.0版本账户余额入口
balance_entry5='com.tongbanjie.android:id/account_balance_layout'
#4.1，4.2账户余额模块按钮
rl_account_balance='com.tongbanjie.android:id/rl_account_balance'#'com.tongbanjie.android:id/account_balance_layout'
#余额数值
rl_payment_details='com.tongbanjie.android:id/rl_payment_details'
#充值按钮
rl_recharge='com.tongbanjie.android:id/rl_recharge'
#输入充值金额
czje="//android.view.View[contains(@content-desc,'充值金额')]/following-sibling::android.widget.EditText"
#提交
recharge_submit="//android.widget.Button[contains(@content-desc,'提')]"
#充值处的提示，请输入正确充值金额
send_true_monkey="//android.view.View[contains(@content-desc,'请输入正确充值金额')]"
#充值处的提示，请选择银行卡
recharge_choose_bankcard="//android.view.View[contains(@content-desc,'请选择银行卡')]"
#充值处的提示，超过该卡累计支付金额
remind_exceed_monkey="//android.view.View[contains(@content-desc,'超过')]"
#代扣测试
withhold_submit="//android.view.View[contains(@content-desc,'代扣测试')]"
#该产品暂不支持购买的提示
product_not_support_buy="//android.view.View[contains(@content-desc,'该产品暂不支持购买')]"
#点击充值或者转出成功的“确定”按钮
click_money_success="//android.view.View/android.widget.Button[@content-desc='确 定']"
#余额转出
rl_balance_out='com.tongbanjie.android:id/rl_balance_out'
#转出金额输入
zcje='//android.widget.EditText[@index=5]'
#转出金额输入-提交
submit='//android.widget.Button[@index=9]'
#校验金额充值/转出成功的按钮
check_money_success="//android.webkit.WebView/android.view.View/android.widget.Button[2]"
check_money_fail='com.tongbanjie.android:id/keyboard'
#校验新用户设置交易密码失败的
check_set_newpeople_tradepwd_fail='com.tongbanjie.android:id/keyboard'
#请输入铜板街交易密码，的确定按钮
click_sure='com.tongbanjie.android:id/confilm_item'
#账户余额显示
balance='com.tongbanjie.android:id/tv_account_balance'

#回款路径
#回款路径未设置文本
label="//android.widget.TextView[@text='请先设置您的交易密码']"
#回款路径模块按钮
return_path_label='com.tongbanjie.android:id/return_path_label'
#银行账户
bank='//android.widget.LinearLayout[@index=2]/android.widget.LinearLayout[@index=1]/android.widget.TextView[@index=0]'
#账户余额
return_path_label_banlance='//android.widget.LinearLayout[@index=1]/android.widget.LinearLayout[@index=1]/android.widget.TextView[@index=0]'
#弹出框的确定以及取消按钮
return_path_label_sure='//android.widget.LinearLayout[@index=3]/android.widget.TextView[@index=2]'
return_path_label_cancel='//android.widget.LinearLayout[@index=3]/android.widget.TextView[@index=0]'

#银行卡管理
#银行卡按钮
rl_bankcard_manager='com.tongbanjie.android:id/rl_bankcard_manager'
#添加银行卡
rlyt_add_bankCard='com.tongbanjie.android:id/rlyt_add_bankCard'
#添加银行卡-姓名
card_name='//android.widget.EditText[contains(@index,4)]'
#添加银行卡-身份证
card_personid='//android.widget.EditText[contains(@index,6)]'
#选择银行
choose_bank='//android.view.View[contains(@index,10)]'
#选择银行 中国银行
choose_one_bank="//android.view.View[contains(@content-desc,'中国银行')]"
#银行卡号
bank_id='//android.widget.EditText[contains(@index,12)]'
#手机号
iphone_num="//android.view.View[contains(@content-desc,'手机号')]/following-sibling::android.widget.EditText"
#绑定
binding="//android.widget.Button[contains(@content-desc,'绑')]"
#输入验证码
send_verify='//android.widget.EditText[@index=26]'
#完成按钮
success_btn='//android.view.View[@index=0]/android.view.View[@index=28]/android.widget.Button[@index=0]'
#成功的文本
success_text='//android.view.View[@index=23]'
#确定
confirm_btn="//android.view.View[@content-desc,'确定']"

#精品推荐购买产品
#精品推荐入口按钮
hot_product='com.tongbanjie.android:id/tab_hot_product_commend'
#精品页的产品
ll_top_content='com.tongbanjie.android:id/ll_top_content'
#精品推荐标题
hot_product_title='com.tongbanjie.android:id/title'
#精品推荐的产品名字
hot_product_name42='com.tongbanjie.android:id/tv_product_name'
#精品推荐的产品期限
hot_product_period='com.tongbanjie.android:id/tv_product_period'
#精品推荐的产品利率

#点击精品推荐页面的购买按钮
hot_product_buy42='com.tongbanjie.android:id/llyt_purchase'
#购买按钮
hot_product_buy_btn='//android.view.View[@index=6]/android.view.View[@index=1]'
#输入金额
hot_product_buy_money='//android.view.View[@index=0]/android.widget.EditText'
#输入金额-付款按钮
hot_product_buy_money_sure='//android.widget.EditText/following-sibling::android.widget.Button'
#选择付款方式
payment_method='com.tongbanjie.android:id/tv_pay_type'
#银行列表
bank_list='//android.view.View/android.widget.ListView/android.view.View'
#银行列表的返回按钮
bankback_btn='//android.view.View[@index=10]'
#选择付款方式上的关闭按钮
close='//android.widget.RelativeLayout[@index=0]/android.widget.ImageView'
#返回
back='//android.view.View[@index=0]/android.view.View[@index=0]'
#tbj键盘
key='com.tongbanjie.android:id/keyboard'
#购买成功后的确定
true='com.tongbanjie.android:id/confilm_item'
#校验购买成功的确定按钮
check_buy_success_btn='//android.view.View/android.widget.Button[2]'
#校验新手理财产品购买成功的按钮
check_newbuy_success_btn='//android.view.View/android.widget.Button[3]'
#失败处理1
#fail1='//android.view.View[@index=0]/android.view.View[@index=18]'
fail1='//android.view.View[@index=0]/android.view.View[@index=12]'
fail2='//android.view.View[@index=0]/android.view.View[@index=13]'
#失败处理2
fail3='//android.view.View[@index=0]/android.view.View[@index=0]/android.view.View[@index=0]'
#计算器按钮
calc_btn='com.tongbanjie.android:id/calc_btn'
#输入计算数值
purchase_amount_edit='com.tongbanjie.android:id/purchase_amount_edit'
#计算
calc_earnings_btn='com.tongbanjie.android:id/calc_earnings_btn'
#关闭计算器
calc_close='com.tongbanjie.android:id/cancle'
#金额不够时，弹出框的确定按钮
bgqd='//android.view.View[@index=0]/android.view.View[@index=12]'
#购买成功后的确定按钮
cgqd="//android.widget.Button[contain(@content-desc,'确定')]"
#理财购买
product_purchase_view='com.tongbanjie.android:id/product_purchase_view'
#新手理财产品的购买提交按钮
newpeople_buy_commit="//android.view.View[@index=0]/android.widget.Button"
#5.0版本理财产品铜宝入口
financing_products_tb='//android.widget.LinearLayout[@index=1]/android.widget.LinearLayout/android.widget.RelativeLayout'
#理财产品
tab_financing_products='com.tongbanjie.android:id/tab_financing_products'
#第一个理财产品
frist_financing_product='//android.widget.LinearLayout[@index=3]/android.widget.LinearLayout/android.widget.RelativeLayout'
#第一个理财产品的名字
frist_financing_product_name='//android.widget.LinearLayout[@index=1]/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[@index=3]/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.TextView[@index=0]'
#新用户才能购买的提示框确定按钮
new_person_sure='//android.widget.TextView[@index=3]'
#5.0理财产品的名称
financing_name='com.tongbanjie.android:id/tv_name'
#5.0版本理财产品名称获取以及默认第一个产品
second_financing_name='//android.widget.LinearLayout[@index=3]/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.RelativeLayout[@index=1]/android.widget.TextView[@index=0]'
second_financing_name_first='//android.widget.LinearLayout[@index=3]/android.widget.LinearLayout[@index=0]'
third_financing_name='//android.widget.LinearLayout[@index=3]/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.RelativeLayout[@index=1]/android.widget.TextView[@index=0]'
third_financing_name_first='//android.widget.LinearLayout[@index=1]/android.widget.LinearLayout[@index=0]'
fourth_financing_name='//android.widget.LinearLayout[@index=4]/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.RelativeLayout[@index=1]/android.widget.TextView[@index=0]'
fourth_financing_name_first='//android.widget.LinearLayout[@index=1]/android.widget.LinearLayout[@index=0]'
#5.0理财产品进入后默认第一个产品
first_financing='//android.widget.LinearLayout[@index=1]/android.widget.LinearLayout'
# 5.0理财产品进入后默认第一个的名称
financing_name_first='//android.widget.LinearLayout[@index=1]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.TextView'
#转让产品立即购买按钮
transfer_buy='com.tongbanjie.android:id/buy'
#转让产品实付按钮
transfer_pay="//android.widget.Button[1]"
#购买流程，输入铜板街交易密码窗口的支付金额定位
commit_money="//android.widget.TextView[@text='支付金额￥2.00']"
#购买流程，没有按规定金额购买的提示
stipulate_money_remind="//android.view.View[contain(@content-desc,'提示')]"
#理财产品的标题处的位置
financing_up='com.tongbanjie.android:id/ll_tongbao'
#理财产品下面的位置
financing_down='//android.widget.LinearLayout[@index=4]/android.widget.LinearLayout/android.widget.RelativeLayout'
#5.0版本理财产品里面的标题
financing_text='com.tongbanjie.android:id/title'
#5.1版本以上精品推荐，新人类型产品
hot_product_new='com.tongbanjie.android:id/btn_new_buy'
#5.1版本以上精品推荐，非新人类型产品
hot_product_tv='com.tongbanjie.android:id/tv_buy'

#我的资产
#我的资产模块按钮
myasset='com.tongbanjie.android:id/tab_my_assets'
#开始赚钱按钮
#start_
#总资产数目
total_assets='com.tongbanjie.android:id/total_assets_value'

#返回
back1='com.tongbanjie.android:id/tv_left_option'
#当前收益
income_component='com.tongbanjie.android:id/income_component'
#累计收益
tv_right_option='com.tongbanjie.android:id/tv_right_option'
#进入铜宝，4.3版本
tongbao_assets_layout43='com.tongbanjie.android:id/tongbao_layout'
#进入铜宝，4.2版本
tongbao_assets_layout42='com.tongbanjie.android:id/tongbao_assets_layout'
#右上角进入购买界面
tv_right_option='com.tongbanjie.android:id/tv_right_option'
#产品详情，资产详情，协议文本，债券明细按钮以及返回
title='com.tongbanjie.android:id/title'
#资产页面，测试产品
zccp='//android.widget.LinearLayout[@index=2]/android.widget.LinearLayout[@index=0]'
#测试产品右上角的购买通道按钮
gmtd='//android.widget.RelativeLayout[@index=3]/android.widget.ImageView[@index=0]'

#产品预告
cpyg='//android.widget.RelativeLayout[@index=4]/android.widget.TextView[contains(@index,1)]'

#关于铜板街
#关于铜板街-进入
rlyt_about_tbj='com.tongbanjie.android:id/rlyt_about_tbj'
#各个id
ljwm='com.tongbanjie.android:id/rlyt_know_about_tbj'
server='com.tongbanjie.android:id/rlyt_customer_service'
pj='com.tongbanjie.android:id/rlyt_remark'
update='com.tongbanjie.android:id/rlyt_check_update'
attention='com.tongbanjie.android:id/rlyt_pay_attention'

#忘记密码后，找回密码
#点击忘记密码
forget_password='com.tongbanjie.android:id/forget_password'
#找回密码
set_login_password='com.tongbanjie.android:id/set_login_password'
#找回密码，下一步按钮
click_back_pwd_nextbtn='com.tongbanjie.android:id/next_btn'
#校验找回密码失败
check_find_pwd='com.tongbanjie.android:id/complete_btn'

#个人信息
#投资风格
nvestment='com.tongbanjie.android:id/rlyt_risk_survey'
#分享按钮
share='com.tongbanjie.android:id/iv_right_option'
#分享到微信平台按钮
share_logo_weixin='com.tongbanjie.android:id/share_logo_weixin'
#分享到微信朋友圈按钮
share_logo_wxfriends='com.tongbanjie.android:id/share_logo_wxfriends'
#朋友圈分享发送
friends_share='com.tencent.mm:id/ee'

#回款路径错误输入交易密码，返回按钮
rl_return_path='com.tongbanjie.android:id/rl_return_path'

#铜宝转入
tongbao_in='com.tongbanjie.android:id/tongbao_in'
#铜宝转出
tongbao_out='com.tongbanjie.android:id/tongbao_out'

#注册没通过校验按钮
sign_fail_check='com.tongbanjie.android:id/tv_left_option'
#校验登陆没通过的按钮
check_login_fail="com.tongbanjie.android:id/text_tip"
#登陆成功校验按钮，更多的文本
login_check='com.tongbanjie.android:id/title'
#注册校验按钮
sign_check='com.tongbanjie.android:id/verify_input'
#购买产品没有跳转到登陆页面
buy_check_login_page_no="//android.widget.Button[contains(@content-desc,'提')]"
#购买铜宝跳转到铜宝页面
buy_tongbao_check='com.tongbanjie.android:id/remind_login'
#跳转到登陆页面按钮
login_page_check='com.tongbanjie.android:id/input_value'
#新手购买 定死的金额
newpeople_buy_check="//android.view.View[@index=4]/android.view.View[@index=1]"
#理财产品的label
financing_label='//android.widget.RelativeLayout[@index=1]/android.widget.TextView'
#校验修改交易密码页面，请输入原交易密码。还停留在该页面
check_old_tradepwd="//android.widget.TextView[@text='请输入原交易密码验证身份']"
#校验修改交易密码页面，请重新设置交易密码。还停留在该页面
check_set_tradepwd="//android.widget.TextView[@text='请重新设置交易密码']"
#校验输入原交易密码错误的弹出框
check_tradepwd_reminder="//android.widget.TextView[@text='提示']"
#校验超过该卡累计支付金额提示框
check_exceed_total_money="//android.view.View[contains(@content-desc,'超过该卡日累计支付金额')]"
#校验交易密码错误，请重新输入的提示框
check_trade_pwd_error="//android.view.View[contains(@content-desc,'交易密码有误')]"
#校验充值失败，请联系客服的提示
check_recharge_fail="//android.view.View[contains(@content-desc,'充值失败，请联系铜板街客服')]"
#校验精品推荐页，购买的提示
check_recommendation_reminder='//android.widget.TextView[@index=1]'
#校验购买提示框
check_buy_box="//android.view.View[contains(@content-desc,'交易密码有误')]"
#提示的确定按钮
reminder_sure_button="//android.view.View[contains(@content-desc,'确定')]"
#理财产品-产品预告的title定位
product_advance_title='//android.view.View[@index=0]/android.view.View[@index=1]'
#理财产品-升级测试的title定位
product_upgrade_title="//android.widget.LinearLayout[@index=3]/android.widget.TextView[@text='稍候升级']"
#充值页面的取消按钮
balance_cancel="//android.view.View/android.view.View[contains(@content-desc,'取消')]"

#5.0理财产品页，产品的定位
finance='com.tongbanjie.android:id/pro_info_layout'
#5.0理财产品页，默认标签的定位
menu_default='com.tongbanjie.android:id/sort_menu_default'
#邀请好友按钮
more_invite='com.tongbanjie.android:id/more_invite_layout'

#理财页下拉刷新提示
pull_to_refresh="//android.widget.TextView[contains(@text,'下拉刷新')]"

#4.2邀请好友
invite='com.tongbanjie.android:id/more_invite_layout'
#4.2产品
pre_sell='com.tongbanjie.android:id/more_pre_sell'
#4.2关于铜板街
about_tbj='com.tongbanjie.android:id/rlyt_about_tbj'
#信息中心按钮
message='com.tongbanjie.android:id/message'
#信息中心-服务中心
server_table='//android.widget.LinearLayout[@index=0]/android.widget.LinearLayout[@index=0]/android.widget.RelativeLayout[@index=0]'
#信息中心-活动攻略
message_bottom='com.tongbanjie.android:id/layout_customemenu'
#信息中心的时间
message_time='com.tongbanjie.android:id/tv_create_date'
#4.2查看交易记录入口
trade_record="//android.widget.RelativeLayout/android.widget.TextView[contains(@text,'查看交易记录')]"
#4.3察看交易记录入口
trade_record43="com.tongbanjie.android:id/transaction_records_layout"
#4.2查看交易记录，以上为全部交易记录
trade_record_footer='com.tongbanjie.android:id/trade_record_footer_tv'
#4.2当前收益
now_income='com.tongbanjie.android:id/income_component'
#4.3当前收益
now_income43='com.tongbanjie.android:id/today_income_profit_layout'
#4.2当前收益产品的名称
product_name='com.tongbanjie.android:id/name'
#4.3当前收益产品的日期
product_time43='com.tongbanjie.android:id/tv_occur_date'
#4.3我的投资的投资金额定位
investment_view_header='com.tongbanjie.android:id/investment_view_header'
#4.2铜宝，查看累计收益
tongbao_income="//android.widget.RelativeLayout/android.widget.TextView[contains(@text,'查看累计收益')]"
#4.2铜宝，收益日期名称
tongbao_time='com.tongbanjie.android:id/name'
#4.2我的资产页面产品名称
myproperty_product_name='com.tongbanjie.android:id/name'
#4.2我的资产页面产品本金
myproperty_bottom_amount='com.tongbanjie.android:id/amount'
#我的资产页面资产产品
myproperty_product='//android.widget.LinearLayout/android.widget.LinearLayout'
#4.2我的资产底部
myproperty_bottom_tab='com.tongbanjie.android:id/bottom_tabs'
#4.3我的T码
TM='com.tongbanjie.android:id/t_code_layout'
#5.1点击登录
click_login51='com.tongbanjie.android:id/rl_user_info'
#5.1更多-设置
set51='com.tongbanjie.android:id/rlyt_settings'
#4.3我的投资
my_investment43='com.tongbanjie.android:id/my_investment_layout'
#理财产品页面的各个产品定位
finance_product='com.tongbanjie.android:id/rl_container'
#4.2理财产品的产品名称
financing_name42='com.tongbanjie.android:id/product_name'
#4.2理财产品页面的产品标题
financing_title='com.tongbanjie.android:id/title'
#4.2购买的提示标题
buy_title_error="//android.view.View[contains(@content-desc,'购买金额需')]"
#4.2新用户购买的提示框
newpeople_buy_commit_title="//android.widget.TextView[contains(@content-desc,'亲，非常抱歉,目前此产品只有新用户才能购买')]"
#4.2货币基金，个人信息的身份证
identity_card="//android.view.View[contains(@content-desc,'身份证')]"
#理财产品的敬请期待提示框
dialog_message="//android.widget.TextView[contains(@text,'敬请期待')]"
#准时开售提示框
sale_on_time="//android.widget.TextView[contains(@text,'准时开售')]"
#服务器出错
server_error="//android.view.View[contains(@content-desc,'服务器出错了')]"
#4.2理财产品-长期在售
long_time_seal="//android.widget.TextView[contains(@text,'长期在售')]"
#5.1精品推荐页面，注册/登录按钮
hot_product_login='com.tongbanjie.android:id/btn_login'
#5.1精品推荐产品抢购或者已抢完的标签
hot_product_buy='com.tongbanjie.android:id/tv_buy'
#5.1精品推荐的产品
hot_product_name='com.tongbanjie.android:id/vg_item'
#5.1精品推荐售罄的提示
seal_message="//android.widget.TextView[contains(@text,'铜板街微信订阅号')]"

#5.1理财产品，产品类型
product_form51='com.tongbanjie.android:id/ll_icon'
#5.1理财产品，产品名称
product_name51='com.tongbanjie.android:id/product_name_tv'
#5.1理财产品，默认
sort_menu_default='com.tongbanjie.android:id/sort_menu_default'
#5.1货架空空
shelf_empty="//android.widget.TextView[contains(@text,'货架空空')]"
#5.1产品预告
product_advance_notice="//android.view.View/android.view.View[contains(@content-desc,'产品预告')]"
#5.2定期理财的标题
terminal_title="//android.widget.TextView[contains(@text,'定期理财')]"
#5.1产品预告-返回
product_advance_notice_back="//android.webkit.WebView/android.view.View[1]/android.view.View[1]"
#5.1理财产品，理财期限
sort_menu_period='com.tongbanjie.android:id/sort_menu_period'
#5.2当前产品最大限额提示框
product_beyond_money="//android.view.View[contains(@content-desc,'当前产品单笔最大限额')]"

#产品预告截图
back2="//android.view.View[contains(@content-desc,'返回')]"

#5.2理财产品标题
finance_lable='//android.widget.LinearLayout/android.widget.LinearLayout/android.widget.RelativeLayout[@index=0]'
#5.2铜宝
tongbao_52='com.tongbanjie.android:id/ll_tongbao'
#5.1更多模块，投资风格
risk='com.tongbanjie.android:id/rlyt_risk_survey'
#5.1更多模块，客户服务
customer_service='com.tongbanjie.android:id/rlyt_customer_service'
#5.1更多模块，评价一下
remark='com.tongbanjie.android:id/rlyt_remark'
#5.1更多模块，设置
settings='com.tongbanjie.android:id/rlyt_settings'
#5.1更多模块，了解我们
about_tbj42='com.tongbanjie.android:id/rlyt_about_tbj'
about_tbj='com.tongbanjie.android:id/rlyt_know_about_tbj'

#该产品剩余金额可买
product_money_buy="//android.view.View[contains(@content-desc,'该产品剩余')]"
#该笔债券已转让的提示
Bond_dialog_message="//android.widget.TextView[contains(@text,'该笔债权已转让')]"

#5.2版本补充铜宝资金按钮
supple_tongbao="//android.widget.Button[contains(@content-desc,'补充铜宝资金')]"

#未持有当前收益提示
not_hold_nowincome="//android.widget.TextView[contains(@text,'您目前未持有资产')]"